wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/binary_accuracy
      5: 1
      6:
      - 1
    - 1: epoch/auc
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_binary_accuracy
      5: 1
      6:
      - 1
    - 1: epoch/val_auc
      5: 1
      6:
      - 1
    - 1: epoch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.16
    start_time: 1680187572.80706
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 7
      - 23
      - 38
      4: 3.9.16
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
