name: nsiete_test
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - aiohttp=3.8.3=py39h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py39haa95532_0
  - blas=1.0=mkl
  - blinker=1.4=py39haa95532_0
  - bottleneck=1.3.5=py39h080aedc_0
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2023.01.10=haa95532_0
  - certifi=2022.12.7=py39haa95532_0
  - cffi=1.15.1=py39h2bbff1b_3
  - colorama=0.4.6=py39haa95532_0
  - cryptography=39.0.1=py39h21b164f_0
  - cuda=11.7.1=0
  - cuda-cccl=11.7.91=0
  - cuda-command-line-tools=11.7.1=0
  - cuda-compiler=11.7.1=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cuobjdump=11.7.91=0
  - cuda-cupti=11.7.101=0
  - cuda-cuxxfilt=11.7.91=0
  - cuda-demo-suite=12.1.55=0
  - cuda-documentation=12.1.55=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight-compute=12.1.0=0
  - cuda-nvcc=11.7.99=0
  - cuda-nvdisasm=12.1.55=0
  - cuda-nvml-dev=11.7.91=0
  - cuda-nvprof=12.1.55=0
  - cuda-nvprune=11.7.91=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-nvvp=12.1.55=0
  - cuda-runtime=11.7.1=0
  - cuda-sanitizer-api=12.1.55=0
  - cuda-toolkit=11.7.1=0
  - cuda-tools=11.7.1=0
  - cuda-visual-tools=11.7.1=0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.3.3=py39h2bbff1b_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h8cc25b3_3
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - hdf5=1.10.6=h1756f20_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py39haa95532_0
  - importlib-metadata=6.0.0=py39haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jpeg=9e=h2bbff1b_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - lerc=3.0=hd77b12b_0
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.2.56=0
  - libcurand-dev=10.3.2.56=0
  - libcurl=7.88.1=h86230a5_0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17=h2bbff1b_0
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libssh2=1.10.0=hcd4344a_0
  - libtiff=4.5.0=h6c2663c_2
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - lz4-c=1.9.4=h2bbff1b_0
  - markdown=3.4.1=py39haa95532_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - multidict=6.0.2=py39h2bbff1b_0
  - nsight-compute=2023.1.0.15=0
  - numexpr=2.8.4=py39h5b0cc5e_0
  - numpy-base=1.23.5=py39h4da318b_0
  - oauthlib=3.2.2=py39haa95532_0
  - openssl=1.1.1t=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - pandas=1.5.2=py39hf11a4ad_0
  - pip=22.3.1=py39haa95532_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py39haa95532_0
  - pyopenssl=23.0.0=py39haa95532_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.16=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - pytorch=1.13.1=py3.9_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h67b0de4_1
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py39haa95532_0
  - setuptools=65.6.3=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h6c2663c_0
  - sqlite=3.40.1=h2bbff1b_0
  - tensorboard-data-server=0.6.1=py39haa95532_0
  - tensorboard-plugin-wit=1.8.1=py39haa95532_0
  - tensorflow-base=2.10.0=mkl_py39h6a7f48e_0
  - tk=8.6.12=h2bbff1b_0
  - typing_extensions=4.4.0=py39haa95532_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.14=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - werkzeug=2.2.3=py39haa95532_0
  - wheel=0.38.4=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - wrapt=1.14.1=py39h2bbff1b_0
  - xz=5.2.10=h8cc25b3_1
  - yarl=1.8.1=py39h2bbff1b_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - absl-py==1.4.0
    - anyio==3.6.2
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - attrs==22.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - cachetools==5.3.0
    - charset-normalizer==3.0.1
    - click==8.1.3
    - comm==0.1.2
    - contourpy==1.0.7
    - cycler==0.11.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - flatbuffers==23.1.21
    - fonttools==4.38.0
    - fqdn==1.5.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.16.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.51.1
    - h5py==3.8.0
    - imageio==2.25.1
    - importlib-resources==5.12.0
    - ipykernel==6.21.2
    - ipython==8.10.0
    - ipython-genutils==0.2.0
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-client==8.0.3
    - jupyter-core==5.2.0
    - jupyter-events==0.6.3
    - jupyter-server==2.3.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - keras==2.11.0
    - kiwisolver==1.4.4
    - libclang==15.0.6.1
    - markupsafe==2.1.2
    - matplotlib==3.7.0
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - nbclassic==0.5.2
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - networkx==3.0
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.24.2
    - packaging==23.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pickleshare==0.7.5
    - pillow==9.4.0
    - platformdirs==3.0.0
    - plotly==5.13.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.36
    - protobuf==3.19.6
    - psutil==5.9.4
    - pure-eval==0.2.2
    - pyasn1-modules==0.2.8
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-json-logger==2.0.6
    - pywavelets==1.4.1
    - pywin32==305
    - pywinpty==2.0.10
    - pyyaml==6.0
    - pyzmq==25.0.0
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.12.2
    - send2trash==1.8.0
    - sentry-sdk==1.15.0
    - setproctitle==1.3.2
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.4
    - stack-data==0.6.2
    - tenacity==8.2.1
    - tensorboard==2.11.2
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-intel==2.11.0
    - tensorflow-io-gcs-filesystem==0.30.0
    - termcolor==2.2.0
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tifffile==2023.2.3
    - tinycss2==1.2.1
    - torch==1.13.1
    - torchaudio==0.13.1
    - torchvision==0.14.1
    - tornado==6.2
    - traitlets==5.9.0
    - typing-extensions==4.5.0
    - uri-template==1.2.0
    - wandb==0.13.10
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - zipp==3.14.0
prefix: C:\Users\vikio\anaconda3\envs\nsiete_test
